### ISSUE TITLE
ImportError: dynamic module does not define init function (init_mixalot_swig)

### ISSUE THREAD

**Issue by asdil12** [unsynchronized/gr-mixalot#4]
```
>>> import mixalot
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/mixalot/__init__.py", line 45, in <module>
    from mixalot_swig import *
  File "/usr/lib/python2.7/site-packages/mixalot/mixalot_swig.py", line 28, in <module>
    _mixalot_swig = swig_import_helper()
  File "/usr/lib/python2.7/site-packages/mixalot/mixalot_swig.py", line 24, in swig_import_helper
    _mod = imp.load_module('_mixalot_swig', fp, pathname, description)
ImportError: dynamic module does not define init function (init_mixalot_swig)
```

**Comment by asdil12** [comment]
Found the problem: It was building against the wrong python (archlinux default to python3).

For the record: This cmake parameters must be used to fix the problem:
```
cmake \
-DPYTHON_EXECUTABLE=$(which python2) \
-DPYTHON_INCLUDE_DIR=$(echo /usr/include/python2*) \
-DPYTHON_LIBRARY=$(echo /usr/lib/libpython2.*.so)
```
