### ISSUE TITLE
ImportError: libgnuradio-mixalot.so.1.0.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by gigibu5** [unsynchronized/gr-mixalot#50]
Hello, 
I have succsessfully installed the library on one system running Ubuntu 22.04. I tried to do the same on my laptop, but when I try to run the script, I get this error:
```
Traceback (most recent call last):
  File "/home/gigibu5/tmp/gr-mixalot/examples/./pocsagtx.py", line 26, in <module>
    import gnuradio.mixalot as mixalot
  File "/usr/local/lib/python3.10/dist-packages/gnuradio/mixalot/__init__.py", line 18, in <module>
    from .mixalot_python import *
ImportError: libgnuradio-mixalot.so.1.0.0: cannot open shared object file: No such file or directory
```
I have installed it using the following steps:
1. cmake .
2. make
3. sudo make install

Thank you for your help.

**Comment by gigibu5** [comment]
Solved issue, looks like make install for some unknown reason didn't copy the `libgnuradio-mixalot.so.1.0.0` into any known lib path. Solved by making a symbolic link from the lib folder in the repository into `/usr/lib`.
