### ISSUE TITLE
pocsagtx_hackrf.grc not working

### ISSUE THREAD

**Issue by mrDevGit** [unsynchronized/gr-mixalot#54]
Hi

It is probably user error but I have got it all set up, no errors but when i set the cap code and freq in gnuradio and hit play, it does not send the message. Or at least, it is not received. 

output on terminal:

Generating: '/home/hero/Downloads/gr-mixalot-main/examples/pocsagtx_hackrf.py'

Executing: /usr/bin/x-terminal-emulator -e /usr/bin/python3 -u /home/hero/Downloads/gr-mixalot-main/examples/pocsagtx_hackrf.py

>>> Done

**Comment by mrDevGit** [comment]
Oh, but when I run the python file on it's own I get this:

./pocsagtx_hackrf.py --help
Traceback (most recent call last):
  File "/home/hero/Downloads/gr-mixalot-main/examples/./pocsagtx_hackrf.py", line 24, in <module>
    import gnuradio.mixalot as mixalot
  File "/usr/local/lib/python3.11/dist-packages/gnuradio/mixalot/__init__.py", line 18, in <module>
    from .mixalot_python import *
ImportError: libgnuradio-mixalot.so.1.0.0: cannot open shared object file: No such file or directory

**Comment by mrDevGit** [comment]
that was resolved by running ldconfig


now when I run it I get:

./pocsagtx_hackrf.py --message 'hello fro gnu'
gr-osmosdr 0.2.0.0 (0.2.0) gnuradio 3.10.5.1
built-in sink types: uhd hackrf bladerf soapy redpitaya freesrp xtrx file 
Using HackRF One with firmware v1.9.1
UUUUUUUUUUUU

**Comment by mrDevGit** [comment]
okay..... so it started working. Only from the command line, sporadically. Only 1 in 2 or 3 messages arrive at the pager. It is not local interference because the message from RPITX works every time to the same pager.

When it does work, I only get the first 2 characters of the message! now I am confused

So from the message above 'hello fro gnu' (that is supposed to be 'from'), only 'he' shows up on the pager. 

Feels like its a weak signal?... Anyone have any ideas on what could be wrong? I'm so close! ;)

**Comment by mrDevGit** [comment]
Any suggestion from anyone that knows Gnuradio better than I do? I bet it is just one of the settings that needs changed...
